-- ISP Looking Glass 核心表结构

CREATE TABLE roles (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  role_name VARCHAR(64) NOT NULL,
  role_code VARCHAR(64) NOT NULL UNIQUE,
  description VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(64) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  email VARCHAR(128),
  mobile VARCHAR(32),
  user_type VARCHAR(16) NOT NULL DEFAULT 'LOCAL',
  role_id BIGINT NOT NULL,
  otp_secret VARCHAR(64),
  status TINYINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE pops (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  pop_code VARCHAR(32) NOT NULL UNIQUE,
  pop_name VARCHAR(128) NOT NULL,
  country VARCHAR(64),
  city VARCHAR(64),
  is_public TINYINT NOT NULL DEFAULT 1,
  status TINYINT NOT NULL DEFAULT 1,
  sort_order INT DEFAULT 0,
  remark VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE devices (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  device_name VARCHAR(128) NOT NULL,
  device_code VARCHAR(64) NOT NULL UNIQUE,
  vendor VARCHAR(64) NOT NULL,
  os_type VARCHAR(64) NOT NULL,
  mgmt_ip VARCHAR(64) NOT NULL,
  ssh_port INT NOT NULL DEFAULT 22,
  username VARCHAR(64) NOT NULL,
  password_encrypted VARBINARY(512),
  private_key_encrypted VARBINARY(2048),
  auth_type VARCHAR(32) NOT NULL,
  pop_id BIGINT NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  priority INT DEFAULT 0,
  timeout_sec INT DEFAULT 10,
  max_concurrency INT DEFAULT 10,
  supported_query_types VARCHAR(255),
  remark VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_devices_pop FOREIGN KEY (pop_id) REFERENCES pops(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE command_templates (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  vendor VARCHAR(64) NOT NULL,
  os_type VARCHAR(64) NOT NULL,
  query_type VARCHAR(64) NOT NULL,
  template_name VARCHAR(128) NOT NULL,
  command_text TEXT NOT NULL,
  parameter_schema JSON NOT NULL,
  is_public TINYINT NOT NULL DEFAULT 1,
  status TINYINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE query_logs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  request_id VARCHAR(64) NOT NULL,
  source_ip VARCHAR(64) NOT NULL,
  user_agent VARCHAR(255),
  query_type VARCHAR(64) NOT NULL,
  query_target VARCHAR(255) NOT NULL,
  query_params_json JSON,
  pop_id BIGINT,
  device_id BIGINT,
  command_template_id BIGINT,
  raw_command TEXT,
  result_status VARCHAR(32),
  result_text MEDIUMTEXT,
  duration_ms INT,
  error_message TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_query_logs_time (created_at),
  INDEX idx_query_logs_type (query_type),
  INDEX idx_query_logs_pop (pop_id),
  INDEX idx_query_logs_device (device_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE system_settings (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  setting_key VARCHAR(128) NOT NULL UNIQUE,
  setting_value TEXT,
  description VARCHAR(255),
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ip_blacklist (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  ip_or_cidr VARCHAR(64) NOT NULL,
  reason VARCHAR(255),
  status TINYINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE announcements (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(128) NOT NULL,
  content TEXT NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  start_at TIMESTAMP NULL,
  end_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
